[theme]
primaryColor = "#28a745"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "Inter"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[logger]
level = "error"

[global]
developmentMode = false
showWarningOnDirectExecution = false

[ui]
hideTopBar = true
