[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1e29"
textColor = "#FAFAFA"
font = "Inter"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
magicEnabled = false

[logger]
level = "error"

[client]
showErrorDetails = false

[global]
developmentMode = false
showWarningOnDirectExecution = false
